### ISSUE TITLE
brunch rpi3 error:  make: *** No targets specified 

### ISSUE THREAD

**Issue by thienpow** [android-raspi/android#1]
![brunch](https://cloud.githubusercontent.com/assets/9796623/20213609/6cb5bfd0-a844-11e6-8746-7617534a98fc.png)

**Comment by humberos** [comment]
Hi there,

There is no problem with build process.
Please, make sure that your build environment is ok by installing Google recommendations here:
https://source.android.com/source/initializing.html

I hope that you get it fixed.

`
    $ sudo apt-get update
`
`
    $ sudo apt-get install openjdk-8-jdk
`

`
$ sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip
`
